"""migrations from server

Revision ID: 84f79f7d5819
Revises: 53c6cdb8fe74
Create Date: 2020-04-19 10:36:58.890623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f79f7d5819'
down_revision = '53c6cdb8fe74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dedication_redmine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee', sa.String(length=140), nullable=True),
    sa.Column('project', sa.String(length=140), nullable=True),
    sa.Column('remarks', sa.String(length=1400), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('dedication', sa.Float(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dedication_redmine_employee'), 'dedication_redmine', ['employee'], unique=False)
    op.create_index(op.f('ix_dedication_redmine_project'), 'dedication_redmine', ['project'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dedication_redmine_project'), table_name='dedication_redmine')
    op.drop_index(op.f('ix_dedication_redmine_employee'), table_name='dedication_redmine')
    op.drop_table('dedication_redmine')
    # ### end Alembic commands ###
